name: e_commerce_data
description: "A package for handling the data layer of the e-commerce app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  http: ^1.3.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  test: ^1.25.15

flutter:
  uses-material-design: true
